server:
  port: 8088

spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://39.107.33.71:3306/lab?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
          username: root
          password: 123456
        slave_1:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://39.107.33.71:3306/lab?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
          username: root
          password: 123456
        slave_2:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://39.107.33.71:3306/lab?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
          username: root
          password: 123456
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: HTML
    encoding: UTF-8
    suffix: .html
    servlet:
      content-type: text/html
  servlet:
    multipart:
      max-file-size: 5242880
      max-request-size: 5242880

logging:
  level:
    root: warn
    com.example.usrweb.dao: trace
  pattern:
    console: '%p%m%n'
#  path: "D:/Projects/Log/test.log"

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
