server:
  port: 8088

spring:
  mvc:
    servlet:
      load-on-startup: 1
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lab?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: HTML
    encoding: UTF-8
    suffix: .html
    servlet:
      content-type: text/html
  servlet:
    multipart:
      max-file-size: 5242880
      max-request-size: 5242880

logging:
  level:
    com.example.usrweb: debug
#  path: "D:/Projects/Log/test.log"

mybatis-plus.mapper-locations=classpath: /dao/impl/*Mapper.xml
mybatis-plus.type-aliases-package: com.example.usrweb.dao